repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.8.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: yarn lint
        language: system
        types: [javascript, typescript]
        pass_filenames: false

      - id: type-check
        name: TypeScript Type Check
        entry: yarn type-check
        language: system
        types: [typescript]
        pass_filenames: false

      - id: security-audit
        name: Security Audit
        entry: yarn security:audit
        language: system
        pass_filenames: false
        stages: [push]